/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiagnosaDBD.View;

import DiagnosaDBD.DiagnosaDBD;
import java.awt.CardLayout;
import java.awt.event.WindowEvent;

/**
 *
 * @author afdallismen
 */
public class GuiDiagnosaDBD extends javax.swing.JFrame {
    DiagnosaDBD app;
    private int countPertanyaan;
    /**
     * Creates new form GuiDiagnosaDBD
     */
    public GuiDiagnosaDBD() {
        initComponents();
    }

    public GuiDiagnosaDBD(DiagnosaDBD app) {
        initComponents();
        this.app = app;
        this.countPertanyaan = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        cbBoxInfoTitle = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPaneInfoDesc = new javax.swing.JTextPane();
        pertanyaan = new javax.swing.JPanel();
        lblNoPertanyaan = new javax.swing.JLabel();
        lblPertanyaan = new javax.swing.JLabel();
        radBtnYa = new javax.swing.JRadioButton();
        radBtnTidak = new javax.swing.JRadioButton();
        btnKembali = new javax.swing.JButton();
        result = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Diagnosa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cardPanel.setLayout(new java.awt.CardLayout());

        welcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 60)); // NOI18N
        jLabel3.setText("Welcome");

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(welcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        cardPanel.add(welcome, "welcome");

        info.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbBoxInfoTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBoxInfoTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxInfoTitleActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(txtPaneInfoDesc);

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(cbBoxInfoTitle, 0, 371, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbBoxInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(info, "info");

        pertanyaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNoPertanyaan.setText("99.");

        lblPertanyaan.setText("Sakit kepala berat atau nyeri kepala ?");

        buttonGroup1.add(radBtnYa);
        radBtnYa.setText("Ya");
        radBtnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnYaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radBtnTidak);
        radBtnTidak.setText("Tidak");
        radBtnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnTidakActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pertanyaanLayout = new javax.swing.GroupLayout(pertanyaan);
        pertanyaan.setLayout(pertanyaanLayout);
        pertanyaanLayout.setHorizontalGroup(
            pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pertanyaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pertanyaanLayout.createSequentialGroup()
                        .addComponent(lblNoPertanyaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pertanyaanLayout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnYa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radBtnTidak)))
                .addContainerGap())
        );
        pertanyaanLayout.setVerticalGroup(
            pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pertanyaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPertanyaan)
                    .addComponent(lblPertanyaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pertanyaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radBtnYa)
                        .addComponent(radBtnTidak))
                    .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        cardPanel.add(pertanyaan, "pertanyaan");

        result.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        result.setPreferredSize(new java.awt.Dimension(376, 240));

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Demam tinggi yang mendadak", "Tidak"},
                {"2", "Sakit kepala berat atau nyeri kepala", "Tidak"},
                {"3", "Nyeri punggung dan nyeri sendi", "Tidak"},
                {"4", "Nyeri ulu hati", "Tidak"},
                {"5", "Sakit perut dan perasaan mual", "Tidak"},
                {"6", "Bintik-bintik merah", "Tidak"},
                {"7", "Pilek", "Tidak"},
                {"8", "Muntah-muntah/diare", "Tidak"}
            },
            new String [] {
                "No", "Pertanyaan", "Jawaban"
            }
        ));
        jScrollPane1.setViewportView(tblResult);
        if (tblResult.getColumnModel().getColumnCount() > 0) {
            tblResult.getColumnModel().getColumn(0).setMaxWidth(40);
            tblResult.getColumnModel().getColumn(1).setMaxWidth(255);
            tblResult.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel4.setText("Hasil diagnosa : ");

        lblResult.setText("Anda tidak mengidap penyakit DBD");

        javax.swing.GroupLayout resultLayout = new javax.swing.GroupLayout(result);
        result.setLayout(resultLayout);
        resultLayout.setHorizontalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addGroup(resultLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResult)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultLayout.setVerticalGroup(
            resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblResult))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        cardPanel.add(result, "result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "info");
        setPanelInfo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "pertanyaan");
        setPanelPertanyaan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        //this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbBoxInfoTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxInfoTitleActionPerformed
        // TODO add your handling code here:
        setTextPaneInfoDesc();
    }//GEN-LAST:event_cbBoxInfoTitleActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        --countPertanyaan;
        setPanelPertanyaan();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void radBtnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnYaActionPerformed
        // TODO add your handling code here:
        app.cPertanyaan.getListPertanyaan().get(countPertanyaan-1)
                .setJawaban(true);
        ++countPertanyaan;
        if (countPertanyaan>app.cPertanyaan.getListPertanyaan().size()){
            countPertanyaan = 1;
            CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
            cardLayout.show(cardPanel, "result");
            setPanelResult();
        } else {
            setPanelPertanyaan();
        }
    }//GEN-LAST:event_radBtnYaActionPerformed

    private void radBtnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnTidakActionPerformed
        // TODO add your handling code here:
        app.cPertanyaan.getListPertanyaan().get(countPertanyaan-1)
                .setJawaban(false);
        ++countPertanyaan;
        if (countPertanyaan>app.cPertanyaan.getListPertanyaan().size()){
            countPertanyaan = 1;
            CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
            cardLayout.show(cardPanel, "result");
            setPanelResult();
        } else {
            setPanelPertanyaan();
        }
    }//GEN-LAST:event_radBtnTidakActionPerformed
    
    public void setLookAndFeel(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiDiagnosaDBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JComboBox cbBoxInfoTitle;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNoPertanyaan;
    private javax.swing.JLabel lblPertanyaan;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel pertanyaan;
    private javax.swing.JRadioButton radBtnTidak;
    private javax.swing.JRadioButton radBtnYa;
    private javax.swing.JPanel result;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextPane txtPaneInfoDesc;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables

    private void setPanelInfo() {
        cbBoxInfoTitle.removeAllItems();
        for ( int i=0; i<app.cInfo.getListInfo().size(); i++){
            cbBoxInfoTitle.addItem(app.cInfo.getListInfo().get(i).getTitle());
        }
        setTextPaneInfoDesc();
        
    }

    private void setTextPaneInfoDesc() {
        String title = (String)cbBoxInfoTitle.getSelectedItem();
        txtPaneInfoDesc.setText(app.cInfo.getInfoByTitle(title).getDesc());
    }

    private void setPanelPertanyaan() {
        btnKembali.setEnabled(true);
    
        if( countPertanyaan == 1){
            btnKembali.setEnabled(false);
        }
        lblNoPertanyaan.setText(Integer.toString(countPertanyaan) + ".");
        lblPertanyaan.setText(app.cPertanyaan.getListPertanyaan()
                .get(countPertanyaan-1).getKuestion());
        //setSelectedRadBtnJawaban(app.cPertanyaan.getListPertanyaan().get(countPertanyaan-1).isJawaban());       
        buttonGroup1.clearSelection();
    }

    private void setSelectedRadBtnJawaban(boolean jawaban) {
        if(jawaban){
            radBtnYa.setSelected(true);
            radBtnTidak.setSelected(false);
        } else {
            radBtnYa.setSelected(false);
            radBtnTidak.setSelected(true);
        }
    }

    private void setPanelResult() {
        for (int i=0; i<tblResult.getRowCount(); i++){
            tblResult.setValueAt(booleanToInd(app.cPertanyaan.getListPertanyaan().get(i).isJawaban()), i, 2);
        }
        if(app.cPertanyaan.getResult()){
            lblResult.setText("Anda mengidap penyakit DBD");
        } else {
            lblResult.setText("Anda tidak mengidap penyakit DBD");
        }
    }

    private Object booleanToInd(boolean jawaban) {
        if (jawaban) {
            return "Ya";
        } else {
            return "Tidak";
        }
    }
}
